"""new fields in user model

Revision ID: d054e35db358
Revises: 476fa74a227e
Create Date: 2020-05-08 22:18:46.107763

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d054e35db358"
down_revision = "476fa74a227e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("about_me", sa.String(length=140), nullable=True))
    op.add_column("user", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_seen")
    op.drop_column("user", "about_me")
    # ### end Alembic commands ###
